# Generated by Django 4.0.4 on 2022-05-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyId', models.CharField(max_length=100)),
                ('rates', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesId', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageUrl', models.CharField(max_length=100)),
                ('lowestPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publisher', models.TextField()),
                ('releaseDate', models.DateField()),
            ],
        ),
    ]
