# Generated by Django 4.0.4 on 2022-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('rates', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
            options={
                'db_table': 'currency',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('currency', models.CharField(max_length=10)),
                ('currentPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageUrl', models.CharField(max_length=100)),
                ('lowestPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publishers', models.TextField()),
                ('releaseDate', models.DateField()),
            ],
            options={
                'db_table': 'games',
                'ordering': ['title'],
            },
        ),
    ]
