# Generated by Django 4.0.4 on 2022-05-21 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listGames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='rates',
            new_name='rate',
        ),
    ]
