# Generated by Django 4.0.4 on 2022-05-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listGames', '0003_alter_currency_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
